# Generated by Django 4.0.5 on 2022-07-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='parents_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
